name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: mkdir Build
    - name: CMake
      run: cmake
    - name: Build
      run: cmake --build Build
